/** every move each species can learn, for the Party & Box move filter.
 *
 * The table is ~500 kB of JSON, so it is NOT imported statically anywhere —
 * `loadLearnsets()` pulls it in its own chunk the first time someone types a
 * move, and everything here degrades to "no answer yet" until it lands.
 * Generated by scripts/import_data.py from the RR dex; keyed by the app's
 * own species names (the importer keys it off types.json's spriteIds, so the
 * alias and alternate-spelling merges done there carry over).
 */

type Entry = {
  /** [move id, level] pairs, lowest level per move */
  l?: [number, number][];
  /** TM/HM move ids */
  t?: number[];
  /** tutor move ids */
  u?: number[];
  /** egg move ids */
  e?: number[];
};

type Raw = {
  moves: Record<string, string>;
  /** move id -> TM number; a move is at most one TM, so it lives here */
  tms: Record<string, number>;
  hms: Record<string, number>;
  species: Record<string, Entry>;
};

/** every way one species can get one move — a move can be several at once
 * (Earthquake is both a level-up move and TM 026 for plenty of mons) */
export type LearnSource = {
  level?: number;
  tm?: number;
  hm?: number;
  tutor?: boolean;
  egg?: boolean;
};

let data: Raw | null = null;
let pending: Promise<void> | null = null;

/** true once the table is in memory; `learnSource` answers null before that */
export const learnsetsReady = () => data !== null;

export function loadLearnsets(): Promise<void> {
  if (data) return Promise.resolve();
  // no retry here on purpose: a failed module import is recorded in the
  // browser's module map, so re-importing the same URL returns the same
  // failure without ever refetching. Reloading is the only real recovery —
  // the same reason lazyView.tsx reloads instead of retrying — and the
  // likeliest cause is the same one: a deploy landing mid-session and
  // taking this chunk's hash with it.
  pending ??= import("../data/learnsets.json").then((m) => {
    data = m.default as unknown as Raw;
  });
  return pending;
}

const fold = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

/** comparison key for a move name — drops case and punctuation, so the calc
 * engine's spelling, the dex's and whatever the player typed all meet */
export const foldMove = fold;

let byMove: Map<string, number[]> | null = null;
let bySpecies: Map<string, Entry> | null = null;
const sourceCache = new Map<string, Map<number, LearnSource>>();

/** move ids for a typed name. Folded, so the calc engine's spelling and the
 * dex's can't drift apart on punctuation ("Will-O-Wisp"), and a name shared
 * by more than one id resolves to all of them. */
function idsFor(name: string): number[] {
  if (!data) return [];
  if (!byMove) {
    byMove = new Map();
    for (const [id, n] of Object.entries(data.moves)) {
      const key = fold(n);
      const list = byMove.get(key);
      if (list) list.push(Number(id));
      else byMove.set(key, [Number(id)]);
    }
  }
  return byMove.get(fold(name)) ?? [];
}

function entryFor(species: string): Entry | undefined {
  if (!data) return undefined;
  const hit = data.species[species];
  if (hit) return hit;
  // a randomizer run can hold a species spelled however the player typed it
  if (!bySpecies) {
    bySpecies = new Map();
    for (const [name, ent] of Object.entries(data.species)) {
      bySpecies.set(fold(name), ent);
    }
  }
  return bySpecies.get(fold(species));
}

function sourcesFor(species: string): Map<number, LearnSource> {
  const cached = sourceCache.get(species);
  if (cached) return cached;
  const out = new Map<number, LearnSource>();
  const ent = entryFor(species);
  if (ent && data) {
    const put = (id: number, patch: LearnSource) => {
      out.set(id, { ...out.get(id), ...patch });
    };
    for (const [id, level] of ent.l ?? []) put(id, { level });
    for (const id of ent.t ?? []) {
      const tm = data.tms[String(id)];
      const hm = data.hms[String(id)];
      put(id, hm ? { hm } : { tm });
    }
    for (const id of ent.u ?? []) put(id, { tutor: true });
    for (const id of ent.e ?? []) put(id, { egg: true });
  }
  sourceCache.set(species, out);
  return out;
}

export interface LearnsetGroups {
  level: { move: string; level: number }[];
  tm: { move: string; num: number }[];
  hm: { move: string; num: number }[];
  tutor: string[];
  egg: string[];
}

/** everything one species can learn, grouped for display — the Pokédex's
 * view of the same table the Party & Box filter queries one move at a time.
 * Null until `loadLearnsets()` has landed. */
export function learnsetFor(species: string): LearnsetGroups | null {
  if (!data) return null;
  const ent = entryFor(species);
  if (!ent) return null;
  const name = (id: number) => data!.moves[String(id)] ?? "";
  const byName = (a: string, b: string) => a.localeCompare(b);
  return {
    level: (ent.l ?? [])
      // the dex records moves a form starts with at level 0 as well as 1;
      // "Lv 0" means nothing to a player, so both read as level 1
      .map(([id, level]) => ({ move: name(id), level: Math.max(1, level) }))
      .filter((m) => m.move)
      .sort((a, b) => a.level - b.level || byName(a.move, b.move)),
    tm: (ent.t ?? [])
      .filter((id) => data!.tms[String(id)])
      .map((id) => ({ move: name(id), num: data!.tms[String(id)] }))
      .sort((a, b) => a.num - b.num),
    hm: (ent.t ?? [])
      .filter((id) => data!.hms[String(id)])
      .map((id) => ({ move: name(id), num: data!.hms[String(id)] }))
      .sort((a, b) => a.num - b.num),
    tutor: (ent.u ?? []).map(name).filter(Boolean).sort(byName),
    egg: (ent.e ?? []).map(name).filter(Boolean).sort(byName),
  };
}

/** same move, however either side spelled it */
export const sameMove = (a: string, b: string) => fold(a) === fold(b);

/** how this species can learn this move, or null for "it can't" / "not
 * loaded yet" — callers gate on `learnsetsReady()` to tell those apart */
export function learnSource(species: string, move: string): LearnSource | null {
  if (!data) return null;
  const sources = sourcesFor(species);
  for (const id of idsFor(move)) {
    const hit = sources.get(id);
    if (hit) return hit;
  }
  return null;
}

/** short pill text: the single most useful thing to say. A level-up leads
 * because it tells you *when*, which no other source can. */
export function sourceLabel(src: LearnSource): string {
  if (src.level !== undefined) return src.level > 1 ? `Lv ${src.level}` : "Lv 1";
  if (src.hm !== undefined) return `HM ${String(src.hm).padStart(2, "0")}`;
  if (src.tm !== undefined) return `TM ${String(src.tm).padStart(3, "0")}`;
  if (src.tutor) return "Tutor";
  if (src.egg) return "Egg";
  return "";
}

/** the full story, for the pill's tooltip */
export function sourceTitle(move: string, src: LearnSource): string {
  const parts: string[] = [];
  if (src.level !== undefined) {
    parts.push(src.level > 1 ? `learns it at level ${src.level}` : "knows it from level 1");
  }
  if (src.tm !== undefined) parts.push(`TM ${String(src.tm).padStart(3, "0")}`);
  if (src.hm !== undefined) parts.push(`HM ${String(src.hm).padStart(2, "0")}`);
  if (src.tutor) parts.push("move tutor");
  if (src.egg) parts.push("egg move");
  return `${move}: ${parts.join(" · ")}`;
}
